version: "3.8"
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ec2,ecs,elbv2,route53,iam,cloudwatch,acm,logs,sts
      - DEBUG=1

  registry:
    image: registry:2
    ports:
      - "5000:5000"
